apiVersion: v1
kind: Namespace
metadata:
  name: namespaceclass-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespaceclass-operator
  namespace: namespaceclass-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceclass-operator-role
rules:
  - apiGroups: ["core.akuity.io"]
    resources: ["namespaceclasses", "namespaceclasses/status", "namespaceclasses/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespaceclass-operator-binding
subjects:
  - kind: ServiceAccount
    name: namespaceclass-operator
    namespace: namespaceclass-operator
roleRef:
  kind: ClusterRole
  name: namespaceclass-operator-role
  apiGroup: rbac.authorization.k8s.io
